### ISSUE TITLE
MODFINDER TROJAN

### ISSUE THREAD

**Issue by Gyran418** [CasDragon/ModFinder#5]
You say it isn't a virus
![Screenshot 2024-06-19 212031](https://github.com/CasDragon/ModFinder/assets/173303497/fafe00ab-2913-42f8-8030-adc3750be27d)

**Comment by CasDragon** [comment]
Looks fine to me? 
https://www.virustotal.com/gui/file/bb113fb61d5da63eb57971b952b91023044ce8d76d256474fd34e28f5d89bcb5?nocache=1
I would recommend you upload the zip file that caused this warning to VirusTotal, and see how they compare, because if you downloaded it from here, you'd see the same results that I just linked to. 

If you are just going to spam because you don't know how anti-virus software works, please don't download files from literally anywhere. You do realize that mods uploaded to Nexus can also contain viruses? (Yes, I did see that you were a commenter who can't follow installation instructions for Toybox)

**Comment by Gyran418** [comment]
I am well aware of potential viruses on nexus and other sites. I came to seek help, not to be treated like shit. I can follow directions and I find your insinuations of not being able to is insulting. the fact you are one of the people who add to this mod has made me decide to not even bother, and don't bother helping people or making mods for others if you are just going to be condescending.
